# Drift build configuration
targets:
  $default:
    builders:
      drift_dev:
        options:
          # Configure database locations for migration tooling
          databases:
            app_database: lib/database/database.dart
          
          # Schema export and migration test configuration
          schema_dir: drift_schemas/
          test_dir: test/database/migrations/
          
          # Store DateTime values as text (ISO 8601 strings) instead of Unix timestamps
          store_date_time_values_as_text: true
