name: foster_squirrel
description: "FosterSquirrel - A Flutter app for wildlife rehabilitators to track baby squirrels' weight, feeding schedules, and care notes."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Database - Drift (modern SQLite wrapper with type-safe queries and automated migrations)
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.8.3
  # Other dependencies
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  fl_chart: ^1.1.1
  provider: ^6.1.1
  uuid: ^4.1.0
  intl: ^0.20.2
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  # Drift code generation
  drift_dev: ^2.20.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/squirrel_no_text.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FCD099"
  adaptive_icon_foreground: "assets/images/squirrel_no_text.png"
  